{"name": "test_002_invalid_login_username", "status": "failed", "statusDetails": {"message": "AssertionError: expected 'Make Appointment' but got Login failed! Please ensure the username and password are valid.\nassert 'Login failed...rd are valid.' == 'Make Appointment'\n  \n  - Make Appointment\n  + Login failed! Please ensure the username and password are valid.", "trace": "self = <tests.test_suite.TestLoginSuite object at 0x107151cd0>\n\n    @pytest.mark.order(2)\n    def test_002_invalid_login_username(self):\n        home_page = HomePage(self.driver, self.wait)  ### homepage initialization\n        home_page.click_make_appointment_button()\n        login_page = LoginPage(self.driver, self.wait)  ## loginpage initialization\n    \n        h2_tag = self.driver.find_element(By.TAG_NAME, 'h2')  # checking to make login indeed showed up\n        assert h2_tag.text == \"Login\", f\"Expected 'Login', but got {h2_tag.text}\"\n        time.sleep(3)\n        ##### starting to enter login information\n        login_page.click_username_field(\"Jojo\")\n        login_page.click_password_field(\"ThisIsNotAPassword\")\n        time.sleep(2)\n        time.sleep(2)\n        login_page.click_login_button()\n        time.sleep(6)\n        h2_tag_3 = self.driver.find_element(By.CSS_SELECTOR, '.lead.text-danger')  ## locating the second element\n>       assert h2_tag_3.text == \"Make Appointment\", f\"expected 'Make Appointment' but got {h2_tag_3.text}\"\nE       AssertionError: expected 'Make Appointment' but got Login failed! Please ensure the username and password are valid.\nE       assert 'Login failed...rd are valid.' == 'Make Appointment'\nE         \nE         - Make Appointment\nE         + Login failed! Please ensure the username and password are valid.\n\ntests/test_suite.py:54: AssertionError"}, "start": 1744256955048, "stop": 1744256968433, "uuid": "8fcee445-3fed-4e29-bec9-4db7daf8afeb", "historyId": "68563a4cc5ee0b8a3c5a2cdf5d3a8617", "testCaseId": "68563a4cc5ee0b8a3c5a2cdf5d3a8617", "fullName": "tests.test_suite.TestLoginSuite#test_002_invalid_login_username", "labels": [{"name": "tag", "value": "order(2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_driver')"}, {"name": "tag", "value": "dependency"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_suite"}, {"name": "subSuite", "value": "TestLoginSuite"}, {"name": "host", "value": "tinos-MBP14"}, {"name": "thread", "value": "19897-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_suite"}]}